### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by vitaly-zdanevich** [organicmaps/organicmaps.github.io#1]
Through [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

I can contribute but where is CSS?

**Comment by rtsisyk** [comment]
The web-site is generated by GitHub Pages / Jekyll by using the default theme. The only way to change css is to create a custom Jekyll theme and add to this repo. We wanted to switch to Hugo instead, but didn't have enough time.

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll
https://jekyllrb.com/

**Comment by vitaly-zdanevich** [comment]
I can move it to Hugo, I have experience with it.

**Comment by rtsisyk** [comment]
It would be great! Please let me know if you need any help.

**Comment by biodranik** [comment]
@vitaly-zdanevich +1 for Hugo! We need to add meta tags to show links to app stores directly in a mobile browser. I can help with review )

**Comment by vitaly-zdanevich** [comment]
ok, I will do it.

**Comment by biodranik** [comment]
Should work now.
