### ISSUE TITLE
Show fees and access tags for POIs

### ISSUE THREAD

**Issue by aronkvh** [organicmaps/organicmaps.github.io#161]
Always needed for parking lots but a lot of other amenities have these tags:
https://wiki.openstreetmap.org/wiki/Key:access
https://wiki.openstreetmap.org/wiki/Key:fee

**Comment by biodranik** [comment]
Please use another repository and check there for related issues: https://github.com/organicmaps/organicmaps/issues?q=is%3Aissue+is%3Aopen+fee+parking
