### ISSUE TITLE
Add mastodon account verification

### ISSUE THREAD

**Issue by benjamin051000** [organicmaps/organicmaps.github.io#166]
See https://docs.joinmastodon.org/user/profile/#verification

**Comment by biodranik** [comment]
Isn't it already verified?
<img width="1024" alt="выява" src="https://github.com/organicmaps/organicmaps.github.io/assets/170263/8e322d70-5b79-4a7e-9c6e-676639d381cd">

**Comment by benjamin051000** [comment]
Weird, I don't see that when viewing it from my account on mastodon.social. This may be a mastodon issue 
![image](https://github.com/organicmaps/organicmaps.github.io/assets/34549440/811e58ca-36a9-41b3-80a6-3a1254d46cd7)

**Comment by benjamin051000** [comment]
Looks like there's a closed issue https://github.com/mastodon/mastodon/issues/19986

I'll close this for now but reopen if I hear anything from over there that might suggest this is an issue with organic maps.
