### ISSUE TITLE
Feature Request: Optional Light Mode

### ISSUE THREAD

**Issue by meenbeese** [organicmaps/organicmaps.github.io#170]
Currently, the website has a dark mode theme which is great for reducing eye strain in low light conditions. However, some users may find that a lighter theme is easier to read in bright light conditions. Therefore, it would be beneficial to include an optional light mode feature.

**Comment by biodranik** [comment]
Isn't the current site theme automatically derived from your system/browser settings?

**Comment by meenbeese** [comment]
> Isn't the current site theme automatically derived from your system/browser settings?

Yes, my bad you are right. I thought the site was always dark as I didn't have my extension which forces dark mode. Will close this issue now.
