### ISSUE TITLE
host copyright.html from /data/

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps.github.io#188]
https://organicmaps.app/terms/
https://github.com/organicmaps/organicmaps/blob/master/data/copyright.html

Currently, the copyright page isn't hosted, and directs to the raw HTML file on github. we should properly host & link to it. (some sort of symlink would be good for automatic updates, but idk if it's possible from another repo)

**Comment by biodranik** [comment]
Why it should be hosted on the web site? That copyright page is about the app, not about the website.

https://htmlpreview.github.io/?https://github.com/organicmaps/organicmaps/master/data/copyright.html
