### ISSUE TITLE
Unable to bookmark locations

### ISSUE THREAD

**Issue by yosimba2000** [organicmaps/organicmaps.github.io#238]
Samsung S10e, Android 12, Organic Maps version 2024.03.31-8

I can't bookmark locations.

1) Open Oganic Maps, tap on a location you want to bookmark.
2) Tap the Star icon, then it brings up your lists.
3) Tap the list you want to add the bookmark to.
4) Nothing happens, nothing is added.

*edit* nevermind ,the star that shows up on the left during a route is not the same as the star for bookmarking. not sure what the star that shows for routing is.

**Comment by pastk** [comment]
The star button in the routing mode allows a user to select an existing bookmark i.e. to set it as a destination or an intermediate point.

**Comment by biodranik** [comment]
When you select a place on the map, the bottom bar should show several buttons (From, To, Save, Share). Are you pressing that star icon Save button? The star becomes yellow, and the bookmark is added/saved. You'll see a pin on the map. 

This issue is not related to the website, so I'll close it.
