### ISSUE TITLE
Turkish translation is not being served

### ISSUE THREAD

**Issue by kaoneko** [organicmaps/organicmaps.github.io#40]
So I'm interested in contributing a Dutch translation of the website and was looking at how this works. I see there's a Turkish translation already, but when I set my browser's preferred language to Turkish, the site is still being served in English. I do get Google.com and the Play Store in Turkish, so I think the fault is not on my end. How does the site decide which language to serve? I'd like to know it's actually working before I put in the effort...

Using Firefox 102.0.1 on Linux, connecting from a... Dutch? IP address.

(I hope we're not deciding the page language based on the client IP; as a VPN user I'm used to websites switching to all kinds of languages, depending on where they think my IP address lives on that particular day.)

**Comment by biodranik** [comment]
I didn't have time yet to activate the translation. It is mentioned in zola's docs.

**Comment by kaoneko** [comment]
Ah, we can also update the file config.toml ourselves (and submit a pull request), I see! That solves that 👍🏻
