### ISSUE TITLE
Disable unneeded GH pages generation

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps.github.io#67]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/1799054/205438198-900da4fd-dbe5-4fd0-94a2-30e9f537e346.png">

**Comment by biodranik** [comment]
Это ты где увидел? Ссылку дашь?

**Comment by rtsisyk** [comment]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/1799054/208232015-7fd9a081-a117-45af-818b-8c13de0e5966.png">

**Comment by biodranik** [comment]
Disabled GH pages master build in the repo settings.
