### ISSUE TITLE
Links always lead to the english page

### ISSUE THREAD

**Issue by Mr-Mime** [organicmaps/organicmaps.github.io#71]
When clicking on a link on any non English start page, it redirects to the English sub page.

Needed change could look like this:

```diff
- (@/donate/index.md)
+ (./donate)
```

or like this:

```diff
- (@/donate/index.md)
+ (@/donate/index.de.md)
```

Which way is wanted?
If I got a response, I can do the changes and create an PR

**Comment by biodranik** [comment]
Great catch! Let's fix it using the second option, it is more explicit.
